[workspace]
resolver = "2"
members = ["crates/latte-hw", "crates/latte-boot"]
exclude = ["resources/upstream"]   # cudzie projekty (fetch.sh) majú vlastné Cargo.toml

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "MIT"
authors = ["Arkay"]

[profile.release]
opt-level = "s"
lto = true
strip = true
